export enum PodcastEventType {
    TRANSCRIPT_CHUNK = "TRANSCRIPT_CHUNK",
    PODCAST_STARTED = "PODCAST_STARTED",
    PODCAST_ENDED = "PODCAST_ENDED",
    AUDIO_CHUNK = "AUDIO_CHUNK",
    AI_RESPONSE = "AI_RESPONSE",
}