import { FastifyInstance } from "fastify";
import { createChannelController, updateChannelController, deleteChannelController, findChannelController, getMyChannelsController, subscribeToChannelController, unsubscribeFromChannelController, getMySubscriptionsController, isSubscribedController } from "./channel.controllers.js";
export async function channelRoutes(fastify:FastifyInstance){
    fastify.post(
        "/",
        {
            preHandler:[fastify.authenticate]
        },
        createChannelController(fastify)
    );
    fastify.put(
        "/:channelId",
        {
            preHandler:[fastify.authenticate,fastify.channelowner]
        },
        updateChannelController(fastify)
    );
    fastify.delete(
        "/:channelId",
        {
            preHandler:[fastify.authenticate,fastify.channelowner]
        },
        deleteChannelController(fastify)
    );
    fastify.get(
        "/:channelId",
        {
            preHandler:[fastify.authenticate]
        },
        findChannelController(fastify)
    );
    fastify.get(
        "/me",
        {
            preHandler:[fastify.authenticate]
        },
        getMyChannelsController(fastify)
    );
    fastify.post(
        "/subscribe/:channelId",
        {
            preHandler:[fastify.authenticate]
        },
        subscribeToChannelController(fastify)
    );
    fastify.post(
        "/unsubscribe/:channelId",
        {
            preHandler:[fastify.authenticate]
        },
        unsubscribeFromChannelController(fastify)
    );
    fastify.get(
        "/subscriptions",
        {
            preHandler:[fastify.authenticate]
        },
        getMySubscriptionsController(fastify)
    );
    fastify.get(
        "/isSubscribed/:channelId",
        {
            preHandler:[fastify.authenticate]
        },
        isSubscribedController(fastify)
    );

}