// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v4.25.3
// source: ai_engine.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientDuplexStream,
  type ClientOptions,
  type handleBidiStreamingCall,
  makeGenericClientConstructor,
  type Metadata,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";

export const protobufPackage = "";

export interface PodcastRequest {
  podcastId: string;
  title: string;
}

export interface PodcastResponse {
  sequence: number;
  transcript: string;
}

function createBasePodcastRequest(): PodcastRequest {
  return { podcastId: "", title: "" };
}

export const PodcastRequest: MessageFns<PodcastRequest> = {
  encode(message: PodcastRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.podcastId !== "") {
      writer.uint32(10).string(message.podcastId);
    }
    if (message.title !== "") {
      writer.uint32(18).string(message.title);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PodcastRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePodcastRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.podcastId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.title = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PodcastRequest {
    return {
      podcastId: isSet(object.podcastId)
        ? globalThis.String(object.podcastId)
        : isSet(object.podcast_id)
        ? globalThis.String(object.podcast_id)
        : "",
      title: isSet(object.title) ? globalThis.String(object.title) : "",
    };
  },

  toJSON(message: PodcastRequest): unknown {
    const obj: any = {};
    if (message.podcastId !== "") {
      obj.podcastId = message.podcastId;
    }
    if (message.title !== "") {
      obj.title = message.title;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PodcastRequest>, I>>(base?: I): PodcastRequest {
    return PodcastRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PodcastRequest>, I>>(object: I): PodcastRequest {
    const message = createBasePodcastRequest();
    message.podcastId = object.podcastId ?? "";
    message.title = object.title ?? "";
    return message;
  },
};

function createBasePodcastResponse(): PodcastResponse {
  return { sequence: 0, transcript: "" };
}

export const PodcastResponse: MessageFns<PodcastResponse> = {
  encode(message: PodcastResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.sequence !== 0) {
      writer.uint32(8).uint32(message.sequence);
    }
    if (message.transcript !== "") {
      writer.uint32(18).string(message.transcript);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PodcastResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePodcastResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.sequence = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.transcript = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PodcastResponse {
    return {
      sequence: isSet(object.sequence) ? globalThis.Number(object.sequence) : 0,
      transcript: isSet(object.transcript) ? globalThis.String(object.transcript) : "",
    };
  },

  toJSON(message: PodcastResponse): unknown {
    const obj: any = {};
    if (message.sequence !== 0) {
      obj.sequence = Math.round(message.sequence);
    }
    if (message.transcript !== "") {
      obj.transcript = message.transcript;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PodcastResponse>, I>>(base?: I): PodcastResponse {
    return PodcastResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PodcastResponse>, I>>(object: I): PodcastResponse {
    const message = createBasePodcastResponse();
    message.sequence = object.sequence ?? 0;
    message.transcript = object.transcript ?? "";
    return message;
  },
};

export type AIEngineService = typeof AIEngineService;
export const AIEngineService = {
  startPodcast: {
    path: "/AIEngine/StartPodcast" as const,
    requestStream: true as const,
    responseStream: true as const,
    requestSerialize: (value: PodcastRequest): Buffer => Buffer.from(PodcastRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): PodcastRequest => PodcastRequest.decode(value),
    responseSerialize: (value: PodcastResponse): Buffer => Buffer.from(PodcastResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): PodcastResponse => PodcastResponse.decode(value),
  },
} as const;

export interface AIEngineServer extends UntypedServiceImplementation {
  startPodcast: handleBidiStreamingCall<PodcastRequest, PodcastResponse>;
}

export interface AIEngineClient extends Client {
  startPodcast(): ClientDuplexStream<PodcastRequest, PodcastResponse>;
  startPodcast(options: Partial<CallOptions>): ClientDuplexStream<PodcastRequest, PodcastResponse>;
  startPodcast(metadata: Metadata, options?: Partial<CallOptions>): ClientDuplexStream<PodcastRequest, PodcastResponse>;
}

export const AIEngineClient = makeGenericClientConstructor(AIEngineService, "AIEngine") as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): AIEngineClient;
  service: typeof AIEngineService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
