// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v4.25.3
// source: auth.proto
/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { makeGenericClientConstructor, } from "@grpc/grpc-js";
export const protobufPackage = "auth";
function createBaseValidateTokenRequest() {
    return { token: "" };
}
export const ValidateTokenRequest = {
    encode(message, writer = new BinaryWriter()) {
        if (message.token !== "") {
            writer.uint32(10).string(message.token);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseValidateTokenRequest();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.token = reader.string();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return { token: isSet(object.token) ? globalThis.String(object.token) : "" };
    },
    toJSON(message) {
        const obj = {};
        if (message.token !== "") {
            obj.token = message.token;
        }
        return obj;
    },
    create(base) {
        return ValidateTokenRequest.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseValidateTokenRequest();
        message.token = object.token ?? "";
        return message;
    },
};
function createBaseValidateTokenResponse() {
    return { valid: false, userId: "", sessionId: "", roles: [], expiresAt: 0, error: "" };
}
export const ValidateTokenResponse = {
    encode(message, writer = new BinaryWriter()) {
        if (message.valid !== false) {
            writer.uint32(8).bool(message.valid);
        }
        if (message.userId !== "") {
            writer.uint32(18).string(message.userId);
        }
        if (message.sessionId !== "") {
            writer.uint32(26).string(message.sessionId);
        }
        for (const v of message.roles) {
            writer.uint32(34).string(v);
        }
        if (message.expiresAt !== 0) {
            writer.uint32(40).int64(message.expiresAt);
        }
        if (message.error !== "") {
            writer.uint32(50).string(message.error);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseValidateTokenResponse();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 8) {
                        break;
                    }
                    message.valid = reader.bool();
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.userId = reader.string();
                    continue;
                }
                case 3: {
                    if (tag !== 26) {
                        break;
                    }
                    message.sessionId = reader.string();
                    continue;
                }
                case 4: {
                    if (tag !== 34) {
                        break;
                    }
                    message.roles.push(reader.string());
                    continue;
                }
                case 5: {
                    if (tag !== 40) {
                        break;
                    }
                    message.expiresAt = longToNumber(reader.int64());
                    continue;
                }
                case 6: {
                    if (tag !== 50) {
                        break;
                    }
                    message.error = reader.string();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            valid: isSet(object.valid) ? globalThis.Boolean(object.valid) : false,
            userId: isSet(object.userId)
                ? globalThis.String(object.userId)
                : isSet(object.user_id)
                    ? globalThis.String(object.user_id)
                    : "",
            sessionId: isSet(object.sessionId)
                ? globalThis.String(object.sessionId)
                : isSet(object.session_id)
                    ? globalThis.String(object.session_id)
                    : "",
            roles: globalThis.Array.isArray(object?.roles) ? object.roles.map((e) => globalThis.String(e)) : [],
            expiresAt: isSet(object.expiresAt)
                ? globalThis.Number(object.expiresAt)
                : isSet(object.expires_at)
                    ? globalThis.Number(object.expires_at)
                    : 0,
            error: isSet(object.error) ? globalThis.String(object.error) : "",
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.valid !== false) {
            obj.valid = message.valid;
        }
        if (message.userId !== "") {
            obj.userId = message.userId;
        }
        if (message.sessionId !== "") {
            obj.sessionId = message.sessionId;
        }
        if (message.roles?.length) {
            obj.roles = message.roles;
        }
        if (message.expiresAt !== 0) {
            obj.expiresAt = Math.round(message.expiresAt);
        }
        if (message.error !== "") {
            obj.error = message.error;
        }
        return obj;
    },
    create(base) {
        return ValidateTokenResponse.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseValidateTokenResponse();
        message.valid = object.valid ?? false;
        message.userId = object.userId ?? "";
        message.sessionId = object.sessionId ?? "";
        message.roles = object.roles?.map((e) => e) || [];
        message.expiresAt = object.expiresAt ?? 0;
        message.error = object.error ?? "";
        return message;
    },
};
function createBaseRegisterRequest() {
    return { firstName: "", lastName: "", email: "", username: "", password: "" };
}
export const RegisterRequest = {
    encode(message, writer = new BinaryWriter()) {
        if (message.firstName !== "") {
            writer.uint32(10).string(message.firstName);
        }
        if (message.lastName !== "") {
            writer.uint32(18).string(message.lastName);
        }
        if (message.email !== "") {
            writer.uint32(26).string(message.email);
        }
        if (message.username !== "") {
            writer.uint32(34).string(message.username);
        }
        if (message.password !== "") {
            writer.uint32(42).string(message.password);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseRegisterRequest();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.firstName = reader.string();
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.lastName = reader.string();
                    continue;
                }
                case 3: {
                    if (tag !== 26) {
                        break;
                    }
                    message.email = reader.string();
                    continue;
                }
                case 4: {
                    if (tag !== 34) {
                        break;
                    }
                    message.username = reader.string();
                    continue;
                }
                case 5: {
                    if (tag !== 42) {
                        break;
                    }
                    message.password = reader.string();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            firstName: isSet(object.firstName)
                ? globalThis.String(object.firstName)
                : isSet(object.first_name)
                    ? globalThis.String(object.first_name)
                    : "",
            lastName: isSet(object.lastName)
                ? globalThis.String(object.lastName)
                : isSet(object.last_name)
                    ? globalThis.String(object.last_name)
                    : "",
            email: isSet(object.email) ? globalThis.String(object.email) : "",
            username: isSet(object.username) ? globalThis.String(object.username) : "",
            password: isSet(object.password) ? globalThis.String(object.password) : "",
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.firstName !== "") {
            obj.firstName = message.firstName;
        }
        if (message.lastName !== "") {
            obj.lastName = message.lastName;
        }
        if (message.email !== "") {
            obj.email = message.email;
        }
        if (message.username !== "") {
            obj.username = message.username;
        }
        if (message.password !== "") {
            obj.password = message.password;
        }
        return obj;
    },
    create(base) {
        return RegisterRequest.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseRegisterRequest();
        message.firstName = object.firstName ?? "";
        message.lastName = object.lastName ?? "";
        message.email = object.email ?? "";
        message.username = object.username ?? "";
        message.password = object.password ?? "";
        return message;
    },
};
function createBaseRegisterResponse() {
    return {
        userId: "",
        username: "",
        email: "",
        role: "",
        accessTokenExpiresAt: 0,
        refreshTokenExpiresAt: 0,
        error: "",
    };
}
export const RegisterResponse = {
    encode(message, writer = new BinaryWriter()) {
        if (message.userId !== "") {
            writer.uint32(10).string(message.userId);
        }
        if (message.username !== "") {
            writer.uint32(18).string(message.username);
        }
        if (message.email !== "") {
            writer.uint32(26).string(message.email);
        }
        if (message.role !== "") {
            writer.uint32(34).string(message.role);
        }
        if (message.accessTokenExpiresAt !== 0) {
            writer.uint32(40).int64(message.accessTokenExpiresAt);
        }
        if (message.refreshTokenExpiresAt !== 0) {
            writer.uint32(48).int64(message.refreshTokenExpiresAt);
        }
        if (message.error !== "") {
            writer.uint32(58).string(message.error);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseRegisterResponse();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.userId = reader.string();
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.username = reader.string();
                    continue;
                }
                case 3: {
                    if (tag !== 26) {
                        break;
                    }
                    message.email = reader.string();
                    continue;
                }
                case 4: {
                    if (tag !== 34) {
                        break;
                    }
                    message.role = reader.string();
                    continue;
                }
                case 5: {
                    if (tag !== 40) {
                        break;
                    }
                    message.accessTokenExpiresAt = longToNumber(reader.int64());
                    continue;
                }
                case 6: {
                    if (tag !== 48) {
                        break;
                    }
                    message.refreshTokenExpiresAt = longToNumber(reader.int64());
                    continue;
                }
                case 7: {
                    if (tag !== 58) {
                        break;
                    }
                    message.error = reader.string();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            userId: isSet(object.userId)
                ? globalThis.String(object.userId)
                : isSet(object.user_id)
                    ? globalThis.String(object.user_id)
                    : "",
            username: isSet(object.username) ? globalThis.String(object.username) : "",
            email: isSet(object.email) ? globalThis.String(object.email) : "",
            role: isSet(object.role) ? globalThis.String(object.role) : "",
            accessTokenExpiresAt: isSet(object.accessTokenExpiresAt)
                ? globalThis.Number(object.accessTokenExpiresAt)
                : isSet(object.access_token_expires_at)
                    ? globalThis.Number(object.access_token_expires_at)
                    : 0,
            refreshTokenExpiresAt: isSet(object.refreshTokenExpiresAt)
                ? globalThis.Number(object.refreshTokenExpiresAt)
                : isSet(object.refresh_token_expires_at)
                    ? globalThis.Number(object.refresh_token_expires_at)
                    : 0,
            error: isSet(object.error) ? globalThis.String(object.error) : "",
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.userId !== "") {
            obj.userId = message.userId;
        }
        if (message.username !== "") {
            obj.username = message.username;
        }
        if (message.email !== "") {
            obj.email = message.email;
        }
        if (message.role !== "") {
            obj.role = message.role;
        }
        if (message.accessTokenExpiresAt !== 0) {
            obj.accessTokenExpiresAt = Math.round(message.accessTokenExpiresAt);
        }
        if (message.refreshTokenExpiresAt !== 0) {
            obj.refreshTokenExpiresAt = Math.round(message.refreshTokenExpiresAt);
        }
        if (message.error !== "") {
            obj.error = message.error;
        }
        return obj;
    },
    create(base) {
        return RegisterResponse.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseRegisterResponse();
        message.userId = object.userId ?? "";
        message.username = object.username ?? "";
        message.email = object.email ?? "";
        message.role = object.role ?? "";
        message.accessTokenExpiresAt = object.accessTokenExpiresAt ?? 0;
        message.refreshTokenExpiresAt = object.refreshTokenExpiresAt ?? 0;
        message.error = object.error ?? "";
        return message;
    },
};
function createBaseLoginRequest() {
    return { email: "", password: "" };
}
export const LoginRequest = {
    encode(message, writer = new BinaryWriter()) {
        if (message.email !== "") {
            writer.uint32(10).string(message.email);
        }
        if (message.password !== "") {
            writer.uint32(18).string(message.password);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseLoginRequest();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.email = reader.string();
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.password = reader.string();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            email: isSet(object.email) ? globalThis.String(object.email) : "",
            password: isSet(object.password) ? globalThis.String(object.password) : "",
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.email !== "") {
            obj.email = message.email;
        }
        if (message.password !== "") {
            obj.password = message.password;
        }
        return obj;
    },
    create(base) {
        return LoginRequest.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseLoginRequest();
        message.email = object.email ?? "";
        message.password = object.password ?? "";
        return message;
    },
};
function createBaseLoginResponse() {
    return {
        userId: "",
        username: "",
        email: "",
        role: "",
        accessTokenExpiresAt: 0,
        refreshTokenExpiresAt: 0,
        error: "",
    };
}
export const LoginResponse = {
    encode(message, writer = new BinaryWriter()) {
        if (message.userId !== "") {
            writer.uint32(10).string(message.userId);
        }
        if (message.username !== "") {
            writer.uint32(18).string(message.username);
        }
        if (message.email !== "") {
            writer.uint32(26).string(message.email);
        }
        if (message.role !== "") {
            writer.uint32(34).string(message.role);
        }
        if (message.accessTokenExpiresAt !== 0) {
            writer.uint32(40).int64(message.accessTokenExpiresAt);
        }
        if (message.refreshTokenExpiresAt !== 0) {
            writer.uint32(48).int64(message.refreshTokenExpiresAt);
        }
        if (message.error !== "") {
            writer.uint32(58).string(message.error);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseLoginResponse();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.userId = reader.string();
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.username = reader.string();
                    continue;
                }
                case 3: {
                    if (tag !== 26) {
                        break;
                    }
                    message.email = reader.string();
                    continue;
                }
                case 4: {
                    if (tag !== 34) {
                        break;
                    }
                    message.role = reader.string();
                    continue;
                }
                case 5: {
                    if (tag !== 40) {
                        break;
                    }
                    message.accessTokenExpiresAt = longToNumber(reader.int64());
                    continue;
                }
                case 6: {
                    if (tag !== 48) {
                        break;
                    }
                    message.refreshTokenExpiresAt = longToNumber(reader.int64());
                    continue;
                }
                case 7: {
                    if (tag !== 58) {
                        break;
                    }
                    message.error = reader.string();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            userId: isSet(object.userId)
                ? globalThis.String(object.userId)
                : isSet(object.user_id)
                    ? globalThis.String(object.user_id)
                    : "",
            username: isSet(object.username) ? globalThis.String(object.username) : "",
            email: isSet(object.email) ? globalThis.String(object.email) : "",
            role: isSet(object.role) ? globalThis.String(object.role) : "",
            accessTokenExpiresAt: isSet(object.accessTokenExpiresAt)
                ? globalThis.Number(object.accessTokenExpiresAt)
                : isSet(object.access_token_expires_at)
                    ? globalThis.Number(object.access_token_expires_at)
                    : 0,
            refreshTokenExpiresAt: isSet(object.refreshTokenExpiresAt)
                ? globalThis.Number(object.refreshTokenExpiresAt)
                : isSet(object.refresh_token_expires_at)
                    ? globalThis.Number(object.refresh_token_expires_at)
                    : 0,
            error: isSet(object.error) ? globalThis.String(object.error) : "",
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.userId !== "") {
            obj.userId = message.userId;
        }
        if (message.username !== "") {
            obj.username = message.username;
        }
        if (message.email !== "") {
            obj.email = message.email;
        }
        if (message.role !== "") {
            obj.role = message.role;
        }
        if (message.accessTokenExpiresAt !== 0) {
            obj.accessTokenExpiresAt = Math.round(message.accessTokenExpiresAt);
        }
        if (message.refreshTokenExpiresAt !== 0) {
            obj.refreshTokenExpiresAt = Math.round(message.refreshTokenExpiresAt);
        }
        if (message.error !== "") {
            obj.error = message.error;
        }
        return obj;
    },
    create(base) {
        return LoginResponse.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseLoginResponse();
        message.userId = object.userId ?? "";
        message.username = object.username ?? "";
        message.email = object.email ?? "";
        message.role = object.role ?? "";
        message.accessTokenExpiresAt = object.accessTokenExpiresAt ?? 0;
        message.refreshTokenExpiresAt = object.refreshTokenExpiresAt ?? 0;
        message.error = object.error ?? "";
        return message;
    },
};
function createBaseRefreshRequest() {
    return { refreshToken: "", sessionId: "" };
}
export const RefreshRequest = {
    encode(message, writer = new BinaryWriter()) {
        if (message.refreshToken !== "") {
            writer.uint32(10).string(message.refreshToken);
        }
        if (message.sessionId !== "") {
            writer.uint32(18).string(message.sessionId);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseRefreshRequest();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.refreshToken = reader.string();
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.sessionId = reader.string();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            refreshToken: isSet(object.refreshToken)
                ? globalThis.String(object.refreshToken)
                : isSet(object.refresh_token)
                    ? globalThis.String(object.refresh_token)
                    : "",
            sessionId: isSet(object.sessionId)
                ? globalThis.String(object.sessionId)
                : isSet(object.session_id)
                    ? globalThis.String(object.session_id)
                    : "",
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.refreshToken !== "") {
            obj.refreshToken = message.refreshToken;
        }
        if (message.sessionId !== "") {
            obj.sessionId = message.sessionId;
        }
        return obj;
    },
    create(base) {
        return RefreshRequest.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseRefreshRequest();
        message.refreshToken = object.refreshToken ?? "";
        message.sessionId = object.sessionId ?? "";
        return message;
    },
};
function createBaseRefreshResponse() {
    return { accessTokenExpiresAt: 0, refreshTokenExpiresAt: 0, error: "" };
}
export const RefreshResponse = {
    encode(message, writer = new BinaryWriter()) {
        if (message.accessTokenExpiresAt !== 0) {
            writer.uint32(8).int64(message.accessTokenExpiresAt);
        }
        if (message.refreshTokenExpiresAt !== 0) {
            writer.uint32(16).int64(message.refreshTokenExpiresAt);
        }
        if (message.error !== "") {
            writer.uint32(26).string(message.error);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseRefreshResponse();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 8) {
                        break;
                    }
                    message.accessTokenExpiresAt = longToNumber(reader.int64());
                    continue;
                }
                case 2: {
                    if (tag !== 16) {
                        break;
                    }
                    message.refreshTokenExpiresAt = longToNumber(reader.int64());
                    continue;
                }
                case 3: {
                    if (tag !== 26) {
                        break;
                    }
                    message.error = reader.string();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            accessTokenExpiresAt: isSet(object.accessTokenExpiresAt)
                ? globalThis.Number(object.accessTokenExpiresAt)
                : isSet(object.access_token_expires_at)
                    ? globalThis.Number(object.access_token_expires_at)
                    : 0,
            refreshTokenExpiresAt: isSet(object.refreshTokenExpiresAt)
                ? globalThis.Number(object.refreshTokenExpiresAt)
                : isSet(object.refresh_token_expires_at)
                    ? globalThis.Number(object.refresh_token_expires_at)
                    : 0,
            error: isSet(object.error) ? globalThis.String(object.error) : "",
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.accessTokenExpiresAt !== 0) {
            obj.accessTokenExpiresAt = Math.round(message.accessTokenExpiresAt);
        }
        if (message.refreshTokenExpiresAt !== 0) {
            obj.refreshTokenExpiresAt = Math.round(message.refreshTokenExpiresAt);
        }
        if (message.error !== "") {
            obj.error = message.error;
        }
        return obj;
    },
    create(base) {
        return RefreshResponse.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseRefreshResponse();
        message.accessTokenExpiresAt = object.accessTokenExpiresAt ?? 0;
        message.refreshTokenExpiresAt = object.refreshTokenExpiresAt ?? 0;
        message.error = object.error ?? "";
        return message;
    },
};
function createBaseLogoutRequest() {
    return { sessionId: "" };
}
export const LogoutRequest = {
    encode(message, writer = new BinaryWriter()) {
        if (message.sessionId !== "") {
            writer.uint32(10).string(message.sessionId);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseLogoutRequest();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.sessionId = reader.string();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            sessionId: isSet(object.sessionId)
                ? globalThis.String(object.sessionId)
                : isSet(object.session_id)
                    ? globalThis.String(object.session_id)
                    : "",
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.sessionId !== "") {
            obj.sessionId = message.sessionId;
        }
        return obj;
    },
    create(base) {
        return LogoutRequest.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseLogoutRequest();
        message.sessionId = object.sessionId ?? "";
        return message;
    },
};
function createBaseLogoutResponse() {
    return { success: false, error: "" };
}
export const LogoutResponse = {
    encode(message, writer = new BinaryWriter()) {
        if (message.success !== false) {
            writer.uint32(8).bool(message.success);
        }
        if (message.error !== "") {
            writer.uint32(18).string(message.error);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseLogoutResponse();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 8) {
                        break;
                    }
                    message.success = reader.bool();
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.error = reader.string();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            success: isSet(object.success) ? globalThis.Boolean(object.success) : false,
            error: isSet(object.error) ? globalThis.String(object.error) : "",
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.success !== false) {
            obj.success = message.success;
        }
        if (message.error !== "") {
            obj.error = message.error;
        }
        return obj;
    },
    create(base) {
        return LogoutResponse.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseLogoutResponse();
        message.success = object.success ?? false;
        message.error = object.error ?? "";
        return message;
    },
};
function createBaseGetMeRequest() {
    return { userId: "" };
}
export const GetMeRequest = {
    encode(message, writer = new BinaryWriter()) {
        if (message.userId !== "") {
            writer.uint32(10).string(message.userId);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseGetMeRequest();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.userId = reader.string();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            userId: isSet(object.userId)
                ? globalThis.String(object.userId)
                : isSet(object.user_id)
                    ? globalThis.String(object.user_id)
                    : "",
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.userId !== "") {
            obj.userId = message.userId;
        }
        return obj;
    },
    create(base) {
        return GetMeRequest.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseGetMeRequest();
        message.userId = object.userId ?? "";
        return message;
    },
};
function createBaseGetMeResponse() {
    return { userId: "", username: "", email: "", role: "", firstName: "", lastName: "", error: "" };
}
export const GetMeResponse = {
    encode(message, writer = new BinaryWriter()) {
        if (message.userId !== "") {
            writer.uint32(10).string(message.userId);
        }
        if (message.username !== "") {
            writer.uint32(18).string(message.username);
        }
        if (message.email !== "") {
            writer.uint32(26).string(message.email);
        }
        if (message.role !== "") {
            writer.uint32(34).string(message.role);
        }
        if (message.firstName !== "") {
            writer.uint32(42).string(message.firstName);
        }
        if (message.lastName !== "") {
            writer.uint32(50).string(message.lastName);
        }
        if (message.error !== "") {
            writer.uint32(58).string(message.error);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseGetMeResponse();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.userId = reader.string();
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.username = reader.string();
                    continue;
                }
                case 3: {
                    if (tag !== 26) {
                        break;
                    }
                    message.email = reader.string();
                    continue;
                }
                case 4: {
                    if (tag !== 34) {
                        break;
                    }
                    message.role = reader.string();
                    continue;
                }
                case 5: {
                    if (tag !== 42) {
                        break;
                    }
                    message.firstName = reader.string();
                    continue;
                }
                case 6: {
                    if (tag !== 50) {
                        break;
                    }
                    message.lastName = reader.string();
                    continue;
                }
                case 7: {
                    if (tag !== 58) {
                        break;
                    }
                    message.error = reader.string();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            userId: isSet(object.userId)
                ? globalThis.String(object.userId)
                : isSet(object.user_id)
                    ? globalThis.String(object.user_id)
                    : "",
            username: isSet(object.username) ? globalThis.String(object.username) : "",
            email: isSet(object.email) ? globalThis.String(object.email) : "",
            role: isSet(object.role) ? globalThis.String(object.role) : "",
            firstName: isSet(object.firstName)
                ? globalThis.String(object.firstName)
                : isSet(object.first_name)
                    ? globalThis.String(object.first_name)
                    : "",
            lastName: isSet(object.lastName)
                ? globalThis.String(object.lastName)
                : isSet(object.last_name)
                    ? globalThis.String(object.last_name)
                    : "",
            error: isSet(object.error) ? globalThis.String(object.error) : "",
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.userId !== "") {
            obj.userId = message.userId;
        }
        if (message.username !== "") {
            obj.username = message.username;
        }
        if (message.email !== "") {
            obj.email = message.email;
        }
        if (message.role !== "") {
            obj.role = message.role;
        }
        if (message.firstName !== "") {
            obj.firstName = message.firstName;
        }
        if (message.lastName !== "") {
            obj.lastName = message.lastName;
        }
        if (message.error !== "") {
            obj.error = message.error;
        }
        return obj;
    },
    create(base) {
        return GetMeResponse.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseGetMeResponse();
        message.userId = object.userId ?? "";
        message.username = object.username ?? "";
        message.email = object.email ?? "";
        message.role = object.role ?? "";
        message.firstName = object.firstName ?? "";
        message.lastName = object.lastName ?? "";
        message.error = object.error ?? "";
        return message;
    },
};
export const AuthServiceService = {
    validateToken: {
        path: "/auth.AuthService/ValidateToken",
        requestStream: false,
        responseStream: false,
        requestSerialize: (value) => Buffer.from(ValidateTokenRequest.encode(value).finish()),
        requestDeserialize: (value) => ValidateTokenRequest.decode(value),
        responseSerialize: (value) => Buffer.from(ValidateTokenResponse.encode(value).finish()),
        responseDeserialize: (value) => ValidateTokenResponse.decode(value),
    },
    register: {
        path: "/auth.AuthService/Register",
        requestStream: false,
        responseStream: false,
        requestSerialize: (value) => Buffer.from(RegisterRequest.encode(value).finish()),
        requestDeserialize: (value) => RegisterRequest.decode(value),
        responseSerialize: (value) => Buffer.from(RegisterResponse.encode(value).finish()),
        responseDeserialize: (value) => RegisterResponse.decode(value),
    },
    login: {
        path: "/auth.AuthService/Login",
        requestStream: false,
        responseStream: false,
        requestSerialize: (value) => Buffer.from(LoginRequest.encode(value).finish()),
        requestDeserialize: (value) => LoginRequest.decode(value),
        responseSerialize: (value) => Buffer.from(LoginResponse.encode(value).finish()),
        responseDeserialize: (value) => LoginResponse.decode(value),
    },
    refresh: {
        path: "/auth.AuthService/Refresh",
        requestStream: false,
        responseStream: false,
        requestSerialize: (value) => Buffer.from(RefreshRequest.encode(value).finish()),
        requestDeserialize: (value) => RefreshRequest.decode(value),
        responseSerialize: (value) => Buffer.from(RefreshResponse.encode(value).finish()),
        responseDeserialize: (value) => RefreshResponse.decode(value),
    },
    logout: {
        path: "/auth.AuthService/Logout",
        requestStream: false,
        responseStream: false,
        requestSerialize: (value) => Buffer.from(LogoutRequest.encode(value).finish()),
        requestDeserialize: (value) => LogoutRequest.decode(value),
        responseSerialize: (value) => Buffer.from(LogoutResponse.encode(value).finish()),
        responseDeserialize: (value) => LogoutResponse.decode(value),
    },
    getMe: {
        path: "/auth.AuthService/GetMe",
        requestStream: false,
        responseStream: false,
        requestSerialize: (value) => Buffer.from(GetMeRequest.encode(value).finish()),
        requestDeserialize: (value) => GetMeRequest.decode(value),
        responseSerialize: (value) => Buffer.from(GetMeResponse.encode(value).finish()),
        responseDeserialize: (value) => GetMeResponse.decode(value),
    },
};
export const AuthServiceClient = makeGenericClientConstructor(AuthServiceService, "auth.AuthService");
function longToNumber(int64) {
    const num = globalThis.Number(int64.toString());
    if (num > globalThis.Number.MAX_SAFE_INTEGER) {
        throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
    }
    if (num < globalThis.Number.MIN_SAFE_INTEGER) {
        throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
    }
    return num;
}
function isSet(value) {
    return value !== null && value !== undefined;
}
